name: Build

on:
  push:
    branches:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        rust: [stable]

    steps:
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - uses: actions/checkout@v3

    - name: Builder
      run: |
          ./windows-build.bat

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Release Build
        path: ./release